import "./css/style.css";

import { Inter } from "next/font/google";

import Header from "@/components/ui/header";
import Banner from "@/components/banner";
import { ClerkProvider } from "@clerk/nextjs";

import AppProvider from "../context/AppContext";
import { ProductProvider } from "../context/ProductContext";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <AppProvider>
                <ProductProvider>
                    <html lang="en">
                        <body
                            className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
                        >
                            <div className="mx-auto flex flex-col items-center min-h-screen max-w-[1440px] overflow-hidden supports-[overflow:clip]:overflow-clip">
                                <Header />
                                <div className="pt-20 w-full px-4 md:px-12">{children}</div>
                                {/* <Banner /> */}
                            </div>
                        </body>
                    </html>
                </ProductProvider>
            </AppProvider>
        </ClerkProvider>
    );
}
